# Generated by Django 5.0.3 on 2024-06-20 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet_transactions",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
