# Generated by Django 5.0.3 on 2024-05-25 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0007_cart_sizes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="quantity",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
