# Generated by Django 5.0.3 on 2024-06-04 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0024_alter_order_discount_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="discount_amount",
            field=models.IntegerField(default=0),
        ),
    ]
