# Generated by Django 5.0.3 on 2024-06-05 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0025_alter_order_discount_amount"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("method_name", models.CharField(max_length=100)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "transaction_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("paid_at", models.DateTimeField(null=True)),
                ("pending", models.BooleanField(default=True)),
                ("success", models.BooleanField(default=False)),
                ("failed", models.BooleanField(default=False)),
            ],
        ),
    ]
