# Generated by Django 5.0.3 on 2024-06-12 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0029_remove_payment_method_name_order_payment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order_items",
            name="request_cancel",
        ),
        migrations.AddField(
            model_name="order_items",
            name="cancel_reason",
            field=models.TextField(blank=True, null=True),
        ),
    ]
