# Generated by Django 5.0.3 on 2024-06-25 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0033_order_items_refund_processed"),
    ]

    operations = [
        migrations.CreateModel(
            name="Shipping_address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(default=None, max_length=200)),
                ("last_name", models.CharField(default=None, max_length=100)),
                ("email", models.EmailField(default="user@gmail.com", max_length=254)),
                ("house", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("pin_code", models.CharField(max_length=20)),
                ("country", models.CharField(max_length=200)),
                ("mobile_number", models.CharField(max_length=12)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cart.order"
                    ),
                ),
            ],
        ),
    ]
