# Generated by Django 5.0.3 on 2024-06-10 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "adminapp",
            "0008_remove_product_offer_prod_id_delete_category_offer_and_more",
        ),
        ("products", "0010_alter_productsize_size"),
    ]

    operations = [
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "offer_type",
                    models.CharField(
                        choices=[("category", "Category"), ("product", "Product")],
                        max_length=10,
                    ),
                ),
                ("percentage", models.PositiveIntegerField()),
                ("is_active", models.BooleanField(default=True)),
                ("end_date", models.DateTimeField()),
                (
                    "categorys",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="adminapp.category",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                    ),
                ),
            ],
        ),
    ]
