# Generated by Django 5.0.3 on 2024-05-06 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0004_cart_product_cart_quantity_delete_cart_item"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cart",
            old_name="quantity",
            new_name="total",
        ),
    ]
