# Generated by Django 5.0.3 on 2024-05-19 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0006_cart_quantity"),
        ("products", "0008_alter_product_categorys"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="sizes",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.productsize",
            ),
        ),
    ]
