# Generated by Django 5.0.3 on 2024-05-25 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0008_alter_cart_quantity"),
        ("useracc", "0012_alter_register_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payment_method", models.CharField(max_length=100, null=True)),
                (
                    "payment_transaction_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Delivered", "Delivered"),
                            ("Pending", "Pending"),
                            ("Payment Failed", "Payment Failed"),
                            ("Payment Successful", "Payment Successful"),
                            ("Returned", "Returned"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sub_total",
                    models.PositiveBigIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "shipping_charge",
                    models.PositiveBigIntegerField(blank=True, default=0, null=True),
                ),
                ("total", models.IntegerField(default=0)),
                ("paid", models.BooleanField(default=False)),
                (
                    "address",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="useracc.address",
                    ),
                ),
                (
                    "register",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="useracc.register",
                    ),
                ),
            ],
        ),
    ]
