# Generated by Django 5.0.3 on 2024-05-26 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0011_order_items"),
        ("products", "0008_alter_product_categorys"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.addimages",
            ),
        ),
        migrations.DeleteModel(
            name="Order_items",
        ),
    ]
