# Generated by Django 5.0.3 on 2024-05-26 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0012_order_product_delete_order_items"),
        ("products", "0008_alter_product_categorys"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="product",
        ),
        migrations.CreateModel(
            name="Order_items",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Order Placed", "Order Placed"),
                            ("Pending", "Pending"),
                            ("Shipped", "Shipped"),
                            ("Out for Delivery", "Out for Delivery"),
                            ("Delivered", "Delivered"),
                            ("Returned", "Returned"),
                            ("Refunded", "Refunded"),
                            ("Cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "price",
                    models.PositiveBigIntegerField(blank=True, default=0, null=True),
                ),
                ("size", models.CharField(default="S", max_length=12)),
                ("qnty", models.PositiveIntegerField(default=0)),
                ("request_cancel", models.BooleanField(default=False)),
                ("cancel", models.BooleanField(default=False)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order",
                        to="cart.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_order",
                        to="products.addimages",
                    ),
                ),
            ],
        ),
    ]
