# Generated by Django 5.0.3 on 2024-05-26 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0013_remove_order_product_order_items"),
        ("products", "0008_alter_product_categorys"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order_items",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_products",
                to="products.product",
            ),
        ),
    ]
