# Generated by Django 5.0.3 on 2024-05-26 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0014_alter_order_items_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order_items",
            name="size",
            field=models.CharField(default="S", max_length=6),
        ),
    ]
