# Generated by Django 5.0.3 on 2024-05-30 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0015_alter_order_items_size"),
        ("products", "0010_alter_productsize_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.addimages",
            ),
        ),
    ]
