# Generated by Django 5.0.3 on 2024-06-01 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0017_wishlist"),
        ("products", "0010_alter_productsize_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wishlist",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="products.addimages"
            ),
        ),
    ]
