# Generated by Django 5.0.3 on 2024-06-02 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminapp", "0003_coupon_customer_coupon"),
        ("cart", "0020_alter_wishlist_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="applied_coupen",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="adminapp.coupon",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="coupon_appliyed",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="discount_amount",
            field=models.BooleanField(default=True),
        ),
    ]
