# Generated by Django 5.0.3 on 2024-06-03 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0021_order_applied_coupen_order_coupon_appliyed_and_more"),
        ("products", "0010_alter_productsize_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order_items",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_products",
                to="products.addimages",
            ),
        ),
    ]
