# Generated by Django 5.0.3 on 2024-06-04 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0023_order_items_request_return"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="discount_amount",
            field=models.BooleanField(default=0),
        ),
    ]
