# Generated by Django 5.0.3 on 2024-06-08 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0028_payment_paid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="method_name",
        ),
        migrations.AddField(
            model_name="order",
            name="payment",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cart.payment",
            ),
        ),
    ]
