# Generated by Django 5.0.3 on 2024-06-15 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0030_remove_order_items_request_cancel_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_success",
            field=models.BooleanField(default=False),
        ),
    ]
