# Generated by Django 5.0.3 on 2024-06-18 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0031_order_payment_success"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order_items",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_items",
                to="cart.order",
            ),
        ),
    ]
