# Generated by Django 5.0.3 on 2024-06-21 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0032_alter_order_items_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="order_items",
            name="refund_processed",
            field=models.BooleanField(default=False),
        ),
    ]
