# Generated by Django 5.0.3 on 2025-08-21 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0034_shipping_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="order_items",
            name="return_approval_status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Approved", "Approved"),
                    ("Rejected", "Rejected"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="order_items",
            name="return_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order_items",
            name="return_reject_reason",
            field=models.TextField(blank=True, null=True),
        ),
    ]
