# Generated by Django 5.0.3 on 2024-04-14 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_product_img"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="img_height",
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddField(
            model_name="product",
            name="img_width",
            field=models.PositiveIntegerField(default=70),
        ),
    ]
