# Generated by Django 5.0.3 on 2024-05-19 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminapp", "0002_category_is_deleted_category_is_listed"),
        ("products", "0007_alter_addimages_image1_alter_addimages_image2_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="categorys",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cat",
                to="adminapp.category",
            ),
        ),
    ]
