# Generated by Django 5.0.3 on 2024-05-27 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_alter_product_categorys"),
    ]

    operations = [
        migrations.AddField(
            model_name="productsize",
            name="is_available",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="productsize",
            name="product_id",
            field=models.ForeignKey(
                default=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variants",
                to="products.product",
            ),
            preserve_default=False,
        ),
    ]
