# Generated by Django 5.0.3 on 2024-05-28 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_productsize_is_available_productsize_product_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productsize",
            name="size",
            field=models.CharField(max_length=10),
        ),
    ]
