# Generated by Django 5.0.3 on 2024-04-12 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_deleted',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='is_listed',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
