# Generated by Django 5.0.3 on 2024-06-02 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("adminapp", "0003_coupon_customer_coupon"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coupon",
            name="starting_date",
        ),
    ]
