# Generated by Django 5.0.3 on 2024-06-10 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminapp", "0006_remove_category_offer_is_listed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category_offer",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
