# Generated by Django 5.0.3 on 2024-06-10 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("adminapp", "0007_category_offer_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product_offer",
            name="prod_id",
        ),
        migrations.DeleteModel(
            name="Category_offer",
        ),
        migrations.DeleteModel(
            name="Product_offer",
        ),
    ]
