# Generated by Django 5.0.3 on 2024-05-07 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("useracc", "0002_register_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="register",
            name="age",
            field=models.CharField(max_length=3, null=True),
        ),
    ]
