# Generated by Django 5.0.3 on 2024-05-21 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("useracc", "0005_register_dob_register_gender_alter_register_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="register",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                max_length=10,
            ),
        ),
    ]
