# Generated by Django 5.0.3 on 2024-06-14 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0011_product_offer_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="addimages",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
