# Generated by Django 5.0.3 on 2024-06-16 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0012_addimages_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="productsize",
            name="previous_stock",
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
