# Generated by Django 5.0.3 on 2024-06-29 04:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0013_productsize_previous_stock"),
    ]

    operations = [
        migrations.AddField(
            model_name="addimages",
            name="additional_images",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.ImageField(upload_to="product_images/"),
                blank=True,
                null=True,
                size=None,
            ),
        ),
    ]
