# Generated by Django 5.0.3 on 2024-05-22 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("useracc", "0007_address"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="address",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="address",
            name="modified_by",
        ),
    ]
