# Generated by Django 5.0.3 on 2024-05-25 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("useracc", "0009_alter_register_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="register",
            name="mobile",
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
